### ISSUE TITLE
Is equivalent to filter_horizontal in Django admin possible in browsable API?

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#13]
The filter-horizontal functionality is super-nice in the Django admin interface.

Is such a thing possible also in the browsable API UI?

Appropriate fields are ``Costs``, ``Topics``, ``Keywords`` and ``Prerequisites``.

**Comment by bryan-brancotte** [comment]
I usually use https://github.com/davidstutz/bootstrap-multiselect to handle multiple select, I have applied it on master to all select multiple present and futur. Does it addresses the need ?

**Comment by joncison** [comment]
This looks extremely nice, thank-you Bryan!

I guess as a rule we should avoid using third-party packages, but not where it's sensible to do so?  cc @hmenager here for a heads-up.
