### ISSUE TITLE
Text area widgets in browsable API are resizable ... could be better

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#14]
Currently the ``Event`` model fields that are are ``TextField`` _i.e._ ``description`` and ``venue`` are resizable.  It would be better if they were _not_ resizable, instead (ideally) a width that either scales to window size (as for ``CharField``) or which is fixed, and with a vertical scrollbar.

This is not a critical feature, but a "nice to have".

**Comment by bryan-brancotte** [comment]
Extending the textarea to have 4 ou 6 rows is easy (cf 75ee2b38d93c14658d667a0f80175473d075dab8), but I don't think that preventing user from resizing the textarea is a good idea: when the text is too big, scrollbar appears, and as a user I don't like scrollbar and always extends the textarea to see all my text at once.

**Comment by joncison** [comment]
Fair points.  So we leave it as-is.  The 5 line default is good.  I just noticed that you actually get a scrollbar if you exceed 5 lines, which you can make to go away be resizing.
