### ISSUE TITLE
Implement EventDate model (as exemplar of structured data)

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#15]
Next commit (see below) will implement 

```
class EventDate(models.Model):
    """Event date model: Start and end date and time of an event."""

    # dateStart is mandatory (other fields optional)
    dateStart = models.DateField(help_text="The start date of the event.")
    dateEnd = models.DateField(help_text="The end date of the event.")
    timeStart = models.TimeField(help_text="The start time of the event.")
    timeEnd = models.TimeField(help_text="The end time of the event.")

    event = models.ForeignKey(Event, related_name='dates', on_delete=models.CASCADE)
```

An event can have multiple associated ``EventDate`` objects - to handle recurrent events where the description of  the event remains the same, but just date/time information differs. NB. we need to store date/time of _past_ instances of an event as well as _future_ ones.

This is a nice example of where we have structured data, and it raises multiple challenges:
- [x]  Implement EventDate model in models.py
- [x] Enable and test EventDate model in Django admin interface
- [x]  Implement (de)serialisation logic in serializers.py - ensuring JSON object is used for the "dates" field
- [x] Test data entry works via browsable API (api/event/ endpoint) "Raw data" 

The model includes other examples of structured data beyond event data/time information.  Before going too deep, I want to be sure whether the above list is complete and correct, what is technically feasible and sensible to do, and get some advice or examples on how to proceed in a good-practice way.  

May I ask please @bryan-brancotte to take a look?  Thanks a million!

**Comment by bryan-brancotte** [comment]
A quick question as I am leaving for a meeting : did you tried to use [DateTimeField](https://docs.djangoproject.com/fr/3.0/ref/models/fields/#django.db.models.DateTimeField) instead of having both a datefield and time field ?

**Comment by joncison** [comment]
I looked at it, but assumed it would not be appropriate (I could be wrong).  My hunch was that because only ``startDate`` is mandatory, and the other fields (``endDate``, ``startTime`` and ``endTime``) are optional, using ``DateField`` and ``TimeField`` would be the way to go.

**Comment by bryan-brancotte** [comment]
Ok I got the idea behind startDate and startTime.

I have just tested it, and with the browsable API an event can steal an eventDate from an other event. The fault is on the Browsable API and the ForeignKey. Also the API present the primary key not the dates. I tried to use [nested serializer](https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-nested-objects) but then the html interface in the browsable api refuses to render the dates

Maybe we can use a simple ManyToMany in event like for keywords, and the useful CreatableSlugRelatedField ?

**Comment by joncison** [comment]
Trying it now (using CreatableSlugRelatedField) ...

**Comment by bryan-brancotte** [comment]
I was about to work on it, I think we can event create a custom CreatableSlugRelatedField that show and parse dates in the form:
```json
{
"dates": [
        "2020-06-20:8h00-17h00",
        "2020-05-20:8h00-12h"
    ],
}
```

**Comment by joncison** [comment]
Hi Bryan, please go ahead!  But I'm not sure about that solution.   There can be multiple "dates" and within the ``EventDate`` date structure only ``startDate`` is mandatory.  Which could make parsing the field tricky.
 
What I really had in mind was:
```
{
"dates":
[
{"startDate": "...", "startTime": "...", "endDate": "...", "endTime": "..."},
{"startDate": "...", "startTime": "...", "endDate": "...", "endTime": "..."}
],
}
```

(``...`` means a date or time of course)

The thing is, we'll hit the same problem in other areas, where we'd definitely need the field names rendered.  e.g. a ``TrainingEvent`` (which is an ``Event`` but with additional fields) can have 0 or more associated ``TrainingEventMetric`` objects including ``dateStart``, ``dateEnd``, ``numParticipants`` etc.)

**Comment by bryan-brancotte** [comment]
We can have this output with nested model serializer but we then have to write overrite the update() methode of EventSerializer. 

Is having EventDate that are range instead of day really important ? Or just to easy users life ?

**Comment by joncison** [comment]
The crucial thing is that an "event" registered in the catalogue can (not always, but sometimes) correspond to multiple actual occurences of that event at different points in the calendar.  The only thing that distinguishes one of these physical events from another is the start & end date, and possibly start & end time, information.  It was a modelling decision to decouple the basic event info from the date/time info like this - to make the user's life easier where they are registering an event which occurs multiple times (they then only have to provide additional date/time info).   It's important that we retain the date/time information for past events, as well as being able to register multiple future data/time info. for recurrences of an event. 

We could take a quick call if that'd be helpful ... in the meantime I'll dig around in _bio.tools_ and see what @hansioan did in similar situations, in case that's useful.

**Comment by joncison** [comment]
PS.  the decision to make only startDate mandatory and not also endDate was to make it easier for events which occur over a single day only.

**Comment by joncison** [comment]
So a similar situation in _bio.tools_ is the [OtherId model](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/model/resource_model/resource.py#L97-L106) which is included as part of the [Resource model](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/model/resource_model/resource.py#L7).   

The [ResourceSerializer](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/serialization/resource_serialization/resource.py#L216) does indeed include include [OtherIDSerializer](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/serialization/resource_serialization/resource.py#L37-L92)
as a [nested serializer](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/serialization/resource_serialization/resource.py#L250).

**Comment by bryan-brancotte** [comment]
I have implemented the nested serializer in 0edf5a7a0a316ad13d58426f333de039196f8fb0 as presented in https://github.com/joncison/ifbcat-sandbox/issues/15#issuecomment-660944566 note that I also had to create the migration as for the EventDate, so git pull before creating the migration for Organisation

**Comment by joncison** [comment]
brilliant ... just finishing off the Organisation model .... will then pull/take a look

**Comment by bryan-brancotte** [comment]
thanks

**Comment by joncison** [comment]
OK, all good now I think.  

It's working great - thanks a million!  The ``update`` function looks fiddly; fortunately we don't have huge amounts of nested structure in the model. 

The cherry on the cake would be (eventually) to enable a nice date and time picker in the broswable API UI (if such a thing is possible) ... will create a separate issue for that.
