### ISSUE TITLE
 Implementing string list in Django model

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#6]
_Is the way I’ve modelled strings lists sensible?_

The Event entity in the [IFB catalogue model](https://docs.google.com/spreadsheets/d/1tMzwkZINvFTj5mUOCBA8MrR8kxjrD6GRfyqH_mT1pi4/edit#gid=346104586) includes 3 properties (topic, keywords & prerequisite) which are lists of strings (cardinality: 0 to many).  I’ve implemented keywords but before doing topic & prerequisite need some feedback on whether the implementation (below) is the right approach.

In [models.py](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/models.py) I’ve defined Event and EventKeyword classes: 

```
class Event(models.Model):
...

class EventKeyword(models.Model):
...
```

where the ``EventKeyword`` and ``Event`` are connected using a foreign key (many-to-one) relationship defined in ``EventKeyword``:

``event = models.ForeignKey(Event, related_name='keywords', null=True, on_delete=models.CASCADE)``

**Comment by joncison** [comment]
@bryan-brancotte  says ...

"Wrapping the keyword in a class is a good approch as it allows you to handle object (and primary key in db) instead of string which prevent slow down when searching related instance to a given keyword. 

What I do not understand is why linked the keyword to a user, and to a single Event.  EventKeyword should be free of Event, and “keywords=models.ManyToManyField(...)” should be present in event."

**Comment by joncison** [comment]
Hi @bryan-brancotte 

Yeah - what I did originally was not right :)

``EventKeyword`` and ``EventPrerequisite`` now do not include the user profile ID, and are modelled by ``ManyToManyField`` defined in the ``Event`` model.  This also solves another issue I was having (these fields were not appearing in the Django admin interface for the Event model - they do now!)

FYI  keyword and prerequisite strings can be set (in browsable API or Django admin interface) via the Event object, but also have their own endpoints:

api/eventkeyword/
api/eventprerequisite/

This is to allow users to register a bunch of keywords or prerequisites independent of events.  Which could be convenient.  BUT only the superuser has permission to delete a keyword or prerequisite.  I think this is the right behaviour.   cc @hmenager 

Pls. take a second look at the code Bryan (which contains some not-needed and commented out code) and close this issue if you're happy.

**Comment by bryan-brancotte** [comment]
> BUT only the superuser has permission to delete a keyword or prerequisite. 

I would also add that only superuser can edit them

**Comment by joncison** [comment]
Sorry, yes.  That is the current behaviour.  User can only view/create keywords or prerequisites.
