### ISSUE TITLE
Serializers for string lists

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#7]
_Is my serialisation approach for lists of strings sensible?_

I created (in [serializers.py](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/serializers.py)) a serializer for ``EventKeyword``: 

``
class EventKeywordSerializer(serializers.ModelSerializer):
...
``

and the corresponding serialisation code for Event:

``   
keywords = CreatableSlugRelatedField(
    	many=True,
 	read_only=False,
      	slug_field="keyword",
      	queryset=models.EventKeyword.objects.all())
``

where ``CreatableSlugRelatedField`` is derived from ``serializers.SlugRelatedField`` but (unlike ``SlugRelatedField``) creates a new object where one doesn’t already exist (see [stackoverflow](https://stackoverflow.com/questions/28009829/creating-and-saving-foreign-key-objects-using-a-slugrelatedfield/28011896))

**Comment by joncison** [comment]
@bryan-brancotte says 

"I do not see anything wrong, although I did not test it. Keep in mind that the ``self.get_queryset().get(**{self.slug_field: data})`` will try to get THE instance with the value provided in data, i.e: if ``data={‘keyword’:’toto’}`` and there is two ``EventKeyword`` where ``‘keyword’=toto`` (one with userA the other with userB) it will raise an exception as a get return one object.

**Comment by joncison** [comment]
@bryan-brancotte as I understand it, this should be OK as I've defined ``unique=True`` on ``[keyword](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/models.py#L176)`` and ``[prerequisite](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/models.py#L198)`` (in [models.py](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/models.py))

**Comment by bryan-brancotte** [comment]
Indeed it will be ok with `unique=True`

P.S: I wanted to close the issue but I can't

**Comment by joncison** [comment]
Ah, sorry.  I just invited you (plus @hmenager) to the repo ... once you accept I'll set up permissions.

**Comment by bryan-brancotte** [comment]
No problem, just accepted it

**Comment by joncison** [comment]
you are now a "collaborator" @bryan-brancotte so should let you close issues etc.

**Comment by bryan-brancotte** [comment]
thanks !
