### ISSUE TITLE
Remove validate_costs function

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#83]
In ``EventSerializer``

No longer needed I think

**Comment by joncison** [comment]
Hi @bryan-brancotte 

If an invalid ``cost`` string is given (by editing the JSON in "Raw data"), we get this:
![Capture](https://user-images.githubusercontent.com/1506863/92101292-d3c56480-edd4-11ea-93ae-33c6ff05b677.GIF)

It would be nice to replace that with a more helpful message, such as is provided by the (currently commented out) bit of logic in ``EventSerializer``:

```for cost in costs:
        #    if cost.__str__() not in models.EventCost.CostType.values:
        #        msg = 'This field can only contain valid cost strings: ' + ','.join(models.EventCost.CostType.values)
        #        raise serializers.ValidationError(msg)
        # return costs```

To add that, I *think* we'd need to catch an ``ObjectDoesNotExist`` error, but I'm not sure where to catch, or how best to do it in a generic way (there are several enums that would benefit from such informative error messages).  

Please advise!  Not a top priority, but we can expect direct editing of the JSON eventually, so nice to have.  cc @hmenager

**Comment by bryan-brancotte** [comment]
Hi @joncison , what do you think about 219304c ?

**Comment by joncison** [comment]
Very nice !  The solution is not so easy, what you propose looks great.

**Comment by bryan-brancotte** [comment]
Ok, applying it to AudienceType, AudienceRole and Field
