### ISSUE TITLE
Support look-up of keyword by keyword, not pk

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#93]
It could be useful to support look-up by keyword on the ``keyword`` model, e.g. to allow a user to quickly see whether a keyword exists, before adding a bunch of them, or using them etc.

**Comment by joncison** [comment]
Hi @bryan-brancotte 

I notice that the URLs are case-sensitive, e.g. 
http://127.0.0.1:8000/api/keyword/COVID-19/

returns a  result as expected, whereas
http://127.0.0.1:8000/api/keyword/covid-19/

does not return any result.

It would be nice if all URLs in the system can be treated as case-insensitive.  Can this be configured somehow?

**Comment by bryan-brancotte** [comment]
Easier than what I expected

**Comment by joncison** [comment]
Excellent, thanks!
